---
  - hosts: nfs_server
    remote_user: root
    become: yes
    gather_facts: no
    handlers:
      - name: restart nfs server
        listen: "restart-nfs"
        service:
          name: nfs-server
          state: restarted    
    tasks:
      - name: "remove remi repository"
        yum_repository:
          name: remi
          file: /etc/yum.repos.d/remi.repo
          state: absent

      - name: "add epel repository"
        yum_repository:
          name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm"
          file: epel.repo
          state: present
          enabled: yes
          gpgcheck: no
          reposdir: "/etc/yum.repos.d/"

      - name: install nfs
        notify: "restart-nfs"
        dnf:
          name:
            - nfs-utils
            - nfs4-acl-tools
          state: present

      - name: Create mountable dir
        file:
          path: /share
          state: directory
          mode: 755
          owner: root
          group: root

      - name: make sure the mount drive has a filesystem
        filesystem:
          fstype: xfs
          dev: /dev/app_cluster_store/nfs_sharepoint

      - name: set mountpoints
        mount:
          path: /share
          src: /dev/app_cluster_store/nfs_sharepoint
          fstype: xfs
          opts: defaults
          state: mounted

      - name: copy /etc/exports
        template:
          src: exports.j2
          dest: /etc/exports
          owner: root
          group: root