---
- hosts: BS1-APP
  become: yes
  tasks:
  - name:
    lineinfile:
      backup: yes
      path: "/etc/sudoers"
      line: "{{item}}  ALL=(root) NOPASSWD:/bin/su - tomcat"
    with_items:
      - kulla
      - Matgree
      - gded