---
- hosts: peoplesoft_production_app
  become: yes
  gather_facts: no
  tasks:
  - name: "Create a directory in OPT"
    file:
      state: directory
      path: /opt/PeopleSoft1
      owner: psadmin
      group: opc

  - name: "Create a directory in OPT"
    file:
      state: directory
      path: /opt/PeopleSoft2
      owner: psadmin
      group: opc

  - name: "Downlod the Files"
    script: DownloadOraclePS.sh
    args:
      chdir: /opt/PeopleSoft1/

  - name: 'Oracle Client for Linux 64bit'
    get_url:
      url:  "https://wordpress.org/latest.tar.gz"
      dest: /opt/PeopleSoft2/
      mode: 0755
      owner:  psadmin
      group:  opc
