- name: Install CRI-O
  ansible.builtin.dnf:
    name:
     - container-selinux
     - cri-o
    state: present

- name: Enable and start CRI-O
  ansible.builtin.service:
    name: crio
    enabled: yes
    state: started
