- name: Install Kubernetes packages {{ item }}
  ansible.builtin.dnf:
    name:
     - kubelet
     - kubeadm
     - kubectl
    state: present

- name: Configure kubelet for kubeadm
  ansible.builtin.copy:
    owner: root
    group: root
    mode: 0644
    dest: /var/lib/kubelet/config.yaml
    content: |
      # /var/lib/kubelet/config.yaml
      apiVersion: kubelet.config.k8s.io/v1beta1
      kind: KubeletConfiguration
      cgroupDriver: systemd
      containerRuntimeEndpoint: unix:///var/run/crio/crio.sock
      failSwapOn: false
      rotateCertificates: true
      staticPodPath: "/etc/kubernetes/manifests"
      serverTLSBootstrap: true

# - name: Enable and start kubelet
#   ansible.builtin.service:
#     name: kubelet
#     enabled: yes
#     state: started