---
- hosts: k8x77-wrkr-prd
  become: yes
  vars:

    k8s_udp:
      - 2376-2380/udp
      - 10250-10252/udp
      - 10255/udp
      - 6443/udp
      - 7946/udp
      - 4789/udp

    k8s_tcp:
      - 2376-2380/tcp
      - 10250-10252/tcp
      - 10255/tcp
      - 6443/tcp
      - 7946/tcp
      - 4789/tcp

  tasks:
  - name: "Open and http/https ports"
    loop:
      - http
      - https
    firewalld:
      zone: public
      service: "{{ item }}"
      permanent: yes
      state: enabled

  - name: "k8s related TCP ports"
    with_items:
      - "{{ vars['k8s_tcp'] }}"
    firewalld:
      port: "{{ item }}"
      permanent: yes
      state: enabled

  - name: "k8s related UDP ports"
    with_items:
      - "{{ vars['k8s_udp'] }}"
    firewalld:
      port: "{{ item }}"
      permanent: yes
      state: enabled