- name: Turn off swap
  ansible.builtin.command: swapoff -a

- name: Remove swap entries from fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: '^\s*[^#]+\s+swap\s+'
    state: absent
    backrefs: yes
