---
galaxy_info:
  author: VNSK
  description: Install and configure SaltStack on Rocky Linux 9
  license: MIT
  min_ansible_version: "2.12"
  platforms:
    - name: EL
      versions:
        - "9"
        