---
- hosts: "k8x77-wrkr-prd"
  become: yes
  vars_files:
    - ./vars/firewallports.yaml

  tasks:
  - name: "Open and http/https ports"
    loop: "{{ [web_service]|flatten(1) }}"
    firewalld:
      zone: public
      service: "{{ item }}"
      permanent: yes
      state: enabled

  - name: "k8s related TCP/UDP ports"
    with_items:
      - "{{ vars['k8s_udp'] }}"
      - "{{ vars['k8s_tcp'] }}"
    firewalld:
      port: "{{ item }}"
      permanent: yes
      state: enabled

  - name: "Set SELinux to Permissive"
    selinux:
      state: permissive
      policy: targeted