- name: Add CRI-O repository
  ansible.builtin.yum_repository:
    name: cri-o
    description: CRI-O Packages
    baseurl: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{ k8s_pre_setup_cri_o_version }}/{{ k8s_pre_setup_os }}/"
    gpgcheck: yes
    gpgkey: "https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:{{ k8s_pre_setup_cri_o_version }}/{{ k8s_pre_setup_os }}/repodata/repomd.xml.key"
    enabled: yes

- name: Install CRI-O
  ansible.builtin.dnf:
    name: cri-o
    state: present

- name: Enable and start CRI-O
  ansible.builtin.service:
    name: crio
    enabled: yes
    state: started
