- name: Set kernel parameters and modules for Kubernetes
  become: true
  block:

    - name: Ensure required kernel modules load at boot
      ansible.builtin.copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          br_netfilter
        owner: root
        group: root
        mode: '0644'

    - name: Load kernel module br_netfilter immediately
      community.general.modprobe:
        name: br_netfilter
        state: present

    - name: Set sysctl parameters for Kubernetes persistently
      ansible.builtin.copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-iptables = 1
          net.ipv4.ip_forward = 1
        owner: root
        group: root
        mode: '0644'

    - name: Apply sysctl parameters to running system
      ansible.builtin.sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
        reload: yes
      loop:
        - { name: "net.bridge.bridge-nf-call-iptables", value: "1" }
        - { name: "net.ipv4.ip_forward", value: "1" }
