---
- hosts:  BS1-APP
  become: yes
  tasks:
  - name: "Create Groups"
    group:
      state: present
      name: "{{item}}"
    with_items:
      - superadmin
      - appsupport
      - appadmin
      - tomcat
      - dbadmin
  
  - name: "Create Super Admin User"
    user:
      name: "{{item}}"
      state: present
      groups: wheel
      generate_ssh_key : yes
      ssh_key_file: .ssh/{{item}}
      ssh_key_type: rsa
      ssh_key_bits: 2048
      force: yes
    with_items:
      - usrw1
      - usrw2

  
  - name: "Create App Admin"
    user:
      name: "{{item}}"
      state: present
      generate_ssh_key : yes
      ssh_key_file: .ssh/{{item}}
      ssh_key_type: rsa
      ssh_key_bits: 2048
      groups: appsupport , tomcat
      force: yes
    with_items:
      - usrw5
      - usrw3


  - name: "Create App Support"
    user:
      name: "{{item}}"
      state: present
      generate_ssh_key : yes
      ssh_key_file: .ssh/{{item}}
      ssh_key_type: rsa
      ssh_key_bits: 2048
      groups: appsupport , dbadmin
      force: yes
    with_items:
      - usrw1
      - usrw2
      - usrw3
      - usrw4


  - name: "copy files {{item}}"
    copy:
      src: "/root/nallarai/{{item}}.pub"
      dest: "/home/{{item}}/.ssh/authorized_keys"
      owner: "{{item}}"
      group: "{{item}}"
      mode: 0600
    with_items:
      - usrw1
      - usrw2
      - usrw3
      - usrw4