---
- hosts:  BS1-PRD-APP
  become: yes
  tasks:
  - name:
    lineinfile:
      backup: yes
      path: "/etc/sudoers"
      line: "{{item}}     ALL=(root) NOPASSWD: /bin/su - tomcat"
    with_items:
      - usrw1
      - usrw2
      - usrw3
      - usrw4
