---
- hosts: exp_box
  gather_facts: no
  vars_files:
    - ./vars/httpd_vars.yaml

  handlers:

    - name: "Reloaded_Apache2"
      service:
        name: apache2
        state: reloaded

    - name: "Start_Apache2"
      service:
        name: apache2
        state: started
        enabled: yes

    - name: "Restart_Apache2"
      service:
        name: apache2
        state: restarted

  tasks:
    - name: "Install Apache2"
      notify: "Start_Apache2"
      apt:
        name: apache2
        state: present
    
    - name: "Create Application Group"
      group:
        name: g_webapp
        state: present
        system: no
    
    - name: "Create User"
      loop: "{{ [users_apache]|flatten(1) }}"
      user:
        name: "{{ item }}"
        group: g_webapp
        comment: "Application Management User(AMU)"
        home: "/var/www/html/"
        create_home: no
        system: no
        state: present

    - name: "Create a html file"
      file:
        path: "/var/www/html/index.html"
        state: touch
        owner: au_apache
        group: g_webapp
        mode: '0644'
    
    - name: "Add content to the file"
      notify: "Restart_Apache2"
      register: echo_process
      shell: echo "Hey YO!" > index.html
      args:
        chdir: "/var/www/html/"

    - name: "Print Stuff"
      debug:
        var: echo_process.stdout_lines 