- name: Enable IP forwarding at runtime
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: true

- name: Persist net.ipv4.ip_forward setting across reboots
  ansible.builtin.lineinfile:
    path: /etc/sysctl.d/99-ipforward.conf
    line: "net.ipv4.ip_forward = 1"
    create: true
    mode: '0644'

- name: Ensure iptables and required tools are installed
  ansible.builtin.package:
    name:
      - iptables
      - iptables-services
      - iproute
      - kmod
    state: present

- name: Load iptable_nat kernel module
  community.general.modprobe:
    name: iptable_nat
    state: present

- name: Masquerade traffic on eth0 (NAT)
  ansible.builtin.shell: iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
  register: nat_masq_rule
  ignore_errors: false
  changed_when: false

- name: Add MASQUERADE rule to POSTROUTING if not present
  ansible.builtin.shell: iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
  when: nat_masq_rule.rc != 0

- name: Allow forwarding traffic from eth1
  ansible.builtin.shell: iptables -A FORWARD -i eth1 -j ACCEPT
  register: forward_rule
  ignore_errors: false
  changed_when: false

- name: Add FORWARD rule to allow traffic from eth1
  ansible.builtin.shell: iptables -A FORWARD -i eth1 -j ACCEPT
  when: forward_rule.rc != 0

- name: Persist iptables rules
  ansible.builtin.shell: iptables-save > /etc/sysconfig/iptables
  notify: "RSTRT-IPTAB"

- name: Create network files
  ansible.builtin.file:
    path: "/etc/sysconfig/network-scripts/ifcfg-eth1"
    state: touch
    owner: root
    group: root
    mode: '0644'

- name: Configure route for eth1
  ansible.builtin.template:
    src: "templates/ifcfg-eth1.j2"
    dest: "/etc/sysconfig/network-scripts/ifcfg-eth1"
    owner: root
    group: root
    mode: '0644'
