- name: "K8s Worker TCP/UDP ports"
  ansible.posix.firewalld:
    port: "{{ item }}"
    state: enabled
    permanent: yes
  loop: "{{ k8s_worker_ports }}"


- name: Enable and start firewalld
  ansible.builtin.service:
    name: firewalld
    enabled: yes
    state: restarted

    