---
- hosts: servr
  #remote_user: starlord
  become: yes
  gather_facts: yes
  tasks:
  - name: "Deploy Build"
    block:
      - name: "Copy files"
        copy:
          src: "/tmp/gaithonde"
          dest: "/share/file123"
      - debug:
          msg: "Failed to copy"
    rescue:
      - name: "Sync files between two systems"
        loop: "{{ groups['clientr']  }}"
        delegate_to: "{{ item  }}"
        register: Syncfile
        synchronize:
          mode: pull
          src: "/opt/db_backup.sql"
          dest: "/share/db_backup.sql"
          group: yes
          owner: yes
      - debug:
          msg: "Ran a direct Sync"
    always:
      - name: "Runs alwayx"
        file:
          path: "/share/updated"
          state: touch
          modification_time: now
          access_time: now